name: Release Charts

on:
  workflow_dispatch: 
    inputs:
      githubOwner:
        description: 'The Github owner to pull chart releases from'
        required: true
      githubRepo:
        description: 'The Github repo to pull chart releases from'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release
        run: |
          ./release.sh
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_OWNER: "${{ github.event.inputs.githubOwner }}"
          GITHUB_REPO: "${{ github.event.inputs.githubRepo }}"
