name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release
        run: |
          ./release.sh
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
